# Generated by Django 3.1.4 on 2021-01-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0002_exceldata_use_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exceldata',
            old_name='id',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='rawdata',
            old_name='id',
            new_name='key',
        ),
    ]
